#!/bin/sh /etc/rc.common
START=97

start() {
    # Remover módulo anterior
    rmmod v4l2loopback 2>/dev/null
    sleep 1
    
    # Cargar v4l2loopback con capacidades de captura
    insmod /lib/modules/$(uname -r)/v4l2loopback.ko \
        devices=3 \
        video_nr=0,1,2,3 \
        card_label="Cam0","Cam1","Cam2" \
        exclusive_caps=1 \
        max_buffers=2
    
    sleep 2
    
    # Iniciar generadores de video
    for i in 0 1 2 3; do
        # ffmpeg -re -f lavfi -i testsrc=size=640x480:rate=25 \
          #  -f v4l2 -vcodec mjpeg -q:v 5 \
            # /dev/video$i > /var/log/ffmpeg_cam$i.log 2>&1 &
        ffmpeg -loop 1 -i /root/img_cam$i.jpeg \
            -vf scale=640:480 -r 25 \
            -f v4l2 -vcodec mjpeg -q:v 5 /dev/video$i \
            > /var/log/ffmpeg_cam$i.log 2>&1 &
        echo $! >> /var/run/ffmpeg_loopback.pid
    done
}

stop() {
    [ -f /var/run/ffmpeg_loopback.pid ] && xargs -r kill < /var/run/ffmpeg_loopback.pid 2>/dev/null
    killall -q ffmpeg 2>/dev/null
    rm -f /var/run/ffmpeg_loopback.pid
    rmmod v4l2loopback 2>/dev/null
}

restart() {
    stop
    sleep 2
    start
}