#!/bin/sh /etc/rc.common
# OctoBot Modbus/TCP server (:502).
START=96
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/python3 /opt/octobot/robot_modbus_server.py
	procd_set_param env \
		OCTOBOT_BUS_PORT="$(uci -q get octobot.main.bus_port)" \
		OCTOBOT_MODBUS_PORT="$(uci -q get octobot.main.modbus_port)"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
