#!/bin/sh /etc/rc.common
# OctoBot MQTT->serial bridge. Requires mosquitto-nossl on :1883.
START=97
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/python3 /opt/octobot/robot_mqtt_bridge.py
	procd_set_param env \
		OCTOBOT_BUS_PORT="$(uci -q get octobot.main.bus_port)" \
		OCTOBOT_MQTT="$(uci -q get octobot.main.mqtt_host)" \
		OCTOBOT_MQTT_TOPIC="$(uci -q get octobot.main.mqtt_topic)"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
