#!/bin/sh /etc/rc.common
# OctoBot HMI / REST gateway (Flask, :8090).
START=96
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/python3 /opt/octobot/octobot_gateway.py
	procd_set_param env \
		OCTOBOT_BUS_PORT="$(uci -q get octobot.main.bus_port)" \
		OCTOBOT_HTTP_PORT="$(uci -q get octobot.main.http_port)" \
		OCTOBOT_SERIAL="$(uci -q get octobot.main.serial_port)" \
		OCTOBOT_LOG="$(uci -q get octobot.main.log_path)"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
