#!/bin/sh /etc/rc.common
# OctoBot serial broker - single owner of the Arduino tty, raw TCP :2000.
START=95
STOP=10
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/python3 /opt/octobot/serial_bus.py
	procd_set_param env \
		OCTOBOT_SERIAL="$(uci -q get octobot.main.serial_port)" \
		OCTOBOT_USE_HW="$(uci -q get octobot.main.use_real_hardware)" \
		OCTOBOT_BUS_PORT="$(uci -q get octobot.main.bus_port)" \
		OCTOBOT_BAUD="$(uci -q get octobot.main.baud)" \
		OCTOBOT_LOG="$(uci -q get octobot.main.log_path)"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
