#!/bin/sh /etc/rc.common

START=90
STOP=10

start() {    
    echo "[+] Starting busybox ftpd on port 21"
    echo "[+] Anonymous access enabled with write permissions"
    
    tcpsvd -vE 0.0.0.0 21 ftpd -w -a anonymous /opt/oem-updates/pending &
}

stop() {
    echo "[+] Stopping ftpd"
    killall tcpsvd 2>/dev/null
    killall ftpd 2>/dev/null
}

restart() {
    stop
    start
}